name: Typecheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install
        uses: ./.github/composite-actions/pnpm-install

      - run: pnpm run typecheck
